notifications:
  email:
    on_success: never
language: ruby
rvm:
  - 2.1.0
env:
  - DB=mysql2
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database geekcoffee_test'
script: 
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec