defaults: &defaults
  app_name: "Geek Coffee"
  domain: <%= ENV['BASE_URL'] %>
  admin_emails: <%= ENV['admin_emails'] %>
  google_analytics_key: <%= ENV['google_analytics_key'] %>
  default_logo_url: "/images/logo.png"
  email_sender: ""
  google_map_key: <%= ENV['google_map_key'] %>
  facebook_app_id:  <%= ENV['facebook_app_id'] %>
  facebook_secret: <%= ENV['facebook_secret'] %>
  devise_secre_key: <%= ENV['devise_secre_key'] %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults